name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Ping to Render
        run: |
          curl -s https://linebot-co24.onrender.com > /dev/null
          echo "執行時間：$(TZ='Asia/Taipei' date +'%Y-%m-%d %H:%M:%S') 測試成功"
